'use strict';

/**
 * core/grounding-line.js
 *
 * Canonical grounding-line phrasings per language. PQR Criterion 6 requires
 * this exact sentence verbatim in every scenario objective that has a
 * KNOWLEDGE block.
 *
 * Single source of truth. Consumers:
 *   - core/validatorRunner.js → check_kq_knowledge_grounding
 *   - .claude/skills/references/grounding-line.md → regenerated by
 *     scripts/gen-docs.js
 *
 * The translator preserves the exact target-language string from this map
 * verbatim — no paraphrase.
 */

const GROUNDING_LINES = Object.freeze({
    NL: 'Beantwoord de vraag van de klant uitsluitend op basis van de informatie in het KENNIS-blok hierboven. Verzin niets en voeg geen informatie toe die daar niet in staat.',
    FR: "Repondez a la question du client uniquement sur la base des informations du bloc CONNAISSANCES ci-dessus. N'inventez rien et n'ajoutez aucune information qui n'y figure pas.",
    DE: 'Beantworten Sie die Frage des Kunden ausschliesslich auf Grundlage der Informationen im WISSEN-Block oben. Erfinden Sie nichts und fugen Sie keine Informationen hinzu, die dort nicht enthalten sind.',
    EN: "Answer the customer's question using only the information in the KNOWLEDGE block above. Do not infer, add, or invent anything not explicitly stated there.",
});

function getGroundingLine(lang) {
    if (!Object.prototype.hasOwnProperty.call(GROUNDING_LINES, lang)) {
        throw new Error(`getGroundingLine: unknown language "${lang}"`);
    }
    return GROUNDING_LINES[lang];
}

module.exports = { GROUNDING_LINES, getGroundingLine };
