result = {
  sourceId: "+3257351115",
  name: "DIGIPOLIS - LPA_LTSU_GUARD",
  projectId: "117",
  project: "LPA ICT",
  promptLibraryId: "82",
  promptLibrary: "DIGIPOLIS\\LPA\\LTSU",
  supportedLanguages: "NL",
  operations: [
    {
      id: "00000",
      type: "SetAttributes",
      name: "Call Initialization",
      isFirstOperation: true,
      params: {
        RoutingId: "LPA_LTSU_GUARD",
        customerName: "LPA",
        customerProject: "LTSU_GUARD",
        IVREvent: "9999",
        IVRAction: "CT",
        NextStep: "00066",
        LogAttributes:
          "RTDS_ProjectName|Eic_RemoteId|ATTR_RoutingId|ATTR_CallflowId|ATTR_IVREvent|ATTR_IVRAction|ATTR_CQR|ATTR_CQS",
      },
    },
    {
      id: "00066",
      type: "GuardRouting",
      name: "LPA_LTSU_GUARD",
      params: {
        Active: true,
        ConfigId: 11,
        ConfigName: "LPA_LTSU_GUARD",
        DialGuard: "True",
        DialGroup: "SIP_TO_TELENET_DIGIPOLIS_STAD",
        OnHoldAudio: "TENANT_DA_GUARD",
        Timeout: 15,
        RecordVoicemail: true,
        AcceptCallMenu: true,
        SendSMS: true,
        SendMail: true,
        NextStep_Failure: "00067",
        NextStep_Success: "00067",
        NextStep: "00067",
      },
    },
    {
      id: "00067",
      type: "SendEmail",
      name: "Mail-To: LPA_LTSU_GUARD",
      params: {
        Active: "1",
        Subject: "LPA_LTSU_GUARD: Call Report",
        From: "IVR_EVENTS@n-allo.be",
        To: "$(ATTR_EmailTo)",
        CC: "",
        Body: "$(ATTR_EmailBody)",
        Importance: "Normal",
        Attachment: "$(ATTR_EmailAttachment)",
        NextStep_Success: "00068",
        NextStep_Failure: "00068",
        NextStep: "00068",
      },
    },
    {
      id: "00068",
      type: "SendSMS",
      name: "SMS-To: LPA_LTSU_GUARD",
      params: {
        Active: "1",
        ConfigId: "47",
        Routing: "LPA_LTSU_GUARD",
        From: "8850",
        To: "$(ATTR_SMSTo)",
        Body: "$(ATTR_SMSBody)",
        NextStep_Failure: "00099",
        NextStep_Success: "00099",
        NextStep: "00099",
      },
    },
    {
      id: "00099",
      type: "Disconnect",
      name: "RTDS: Disconnect",
      params: {},
    },
  ],
};
