#!/usr/bin/env python3
"""Build the rtds-vocalls-component-gen skill bundle from repo sources.

This is the ONLY writer of the skill's bundled copies. It copies the repo
source files the skill needs into the skill tree, applies the path rewrites
defined in the skill's own ``bundle_paths.py`` (single source of the rewrite
rules), and stamps a generated-file banner on each bundled markdown copy.

Run from the repo root::

    python scripts/build_skill_bundle.py

Idempotent: running twice produces no further diff.

Files inside the skill that have NO repo source (``canonical_helpers.js``,
``node_types.md``, ``operation_bodies/``, ``checklist.md``, ``runtime_pointer.md``,
etc.) are skill-canonical and are intentionally NOT touched here. See the skill's
DEPLOY.md.
"""

import importlib.util
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SKILL = REPO / ".claude" / "skills" / "rtds-vocalls-component-gen"

# Banner stamped at the top of each bundled markdown copy so an agent opening a
# copy is told where the real source lives. JS snapshots are left unbannered
# (a JS comment banner risks confusing the ES5.1 example readers).
BANNER_PREFIX = "<!-- GENERATED by scripts/build_skill_bundle.py"
BANNER = (
    BANNER_PREFIX
    + " — edit the repo source under conventions/ or PROJECT_CONVENTIONS.md, not this copy. -->\n"
)


def _load_replacements():
    """Import REPLACEMENTS from the skill's bundle_paths.py (single source)."""
    bp_path = SKILL / "scripts" / "bundle_paths.py"
    spec = importlib.util.spec_from_file_location("bundle_paths", bp_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.REPLACEMENTS


# (repo-relative source, skill-relative destination, is_markdown)
# Mirrors the DEPLOY.md recipe.
MANIFEST = []

# 14 conventions + PROJECT_CONVENTIONS.md (markdown, get a banner)
for conv in sorted((REPO / "conventions").glob("*.md")):
    MANIFEST.append((f"conventions/{conv.name}", f"conventions/{conv.name}", True))
MANIFEST.append(("PROJECT_CONVENTIONS.md", "PROJECT_CONVENTIONS.md", True))

# Component examples (JS, no banner)
for comp in ("sendSms", "sendMail", "voicemaildetector"):
    MANIFEST.append(
        (f"rtds/components/{comp}.js", f"references/examples/{comp}.js", False)
    )

# Runtime snapshots (JS, no banner) — the committed reference runtime is the
# split rtds_3 (env/helpers/Logger) -> rtds_2 (dispatch engine, getParam) ->
# rtds_1 (varObj schema) trio under projects/rtds-runtime/. The old single-file
# projects/demo/rtds_globalCodeAndHelpers.js is the retired v1 runtime (still has
# resolveTokens / OP_VAR_PREFIX splay, no setupConfig) and is NOT bundled.
MANIFEST.append(
    (
        "projects/rtds-runtime/globalLibraries/active/rtds_3_vocallsEnv.js",
        "references/rtds_3_vocallsEnv.js",
        False,
    )
)
MANIFEST.append(
    (
        "projects/rtds-runtime/globalLibraries/active/rtds_2_runtime.js",
        "references/rtds_2_runtime.js",
        False,
    )
)
MANIFEST.append(
    (
        "projects/rtds-runtime/globalLibraries/active/rtds_1_globalConfig.js",
        "references/rtds_1_globalConfig.js",
        False,
    )
)


def render(src_rel, is_markdown, replacements):
    """Return the bundled content (bytes) for one source file, normalized to LF.

    Newlines are normalized to LF on both read and write. The repo uses
    core.autocrlf=true with no .gitattributes, so working-tree newline style is
    nondeterministic across checkouts; normalizing to LF (what git stores) keeps
    the generator output and check_skill_sync.py stable regardless.
    """
    text = (REPO / src_rel).read_text(encoding="utf-8")
    text = text.replace("\r\n", "\n")
    for old, new in replacements:
        text = text.replace(old, new)
    if is_markdown:
        text = BANNER + text
    return text.encode("utf-8")


def _norm(b):
    return b.replace(b"\r\n", b"\n") if b is not None else None


def build(write=True):
    """Generate the bundle. Returns list of (dest_rel, changed) tuples.

    Comparison is newline-insensitive (LF-normalized). When ``write`` is False,
    reports which destinations would change — used by check_skill_sync.py.
    """
    replacements = _load_replacements()
    results = []
    for src_rel, dst_rel, is_markdown in MANIFEST:
        want = render(src_rel, is_markdown, replacements)
        dst = SKILL / dst_rel
        have = dst.read_bytes() if dst.exists() else None
        changed = _norm(have) != _norm(want)
        if changed and write:
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_bytes(want)
        results.append((dst_rel, changed))
    return results


def main():
    results = build(write=True)
    changed = [d for d, c in results if c]
    for d in changed:
        print("updated", d)
    print(f"Bundle built: {len(changed)} file(s) updated, {len(results)} total.")


if __name__ == "__main__":
    main()
