#!/usr/bin/env python3
"""Generate rtds/docs/operations-catalog.md from per-spec frontmatter.

Each operation spec under ``rtds/specs/*.spec.md`` carries YAML frontmatter that
is the single source of truth for that operation's catalog row. This script
renders the Operations table from that frontmatter and wraps it in the catalog's
fixed prose (header + the two trailing reference sections).

The row ORDER is curated (not alphabetical), so it is kept here in ``ROW_ORDER``.

Run from the repo root::

    python scripts/gen_catalog.py

Idempotent. ``check_lockstep.py`` fails if the committed catalog differs from
this script's output, so a stale catalog cannot silently mislead.

Frontmatter contract (catalog-relevant fields)::

    catalog:
      operation: sendSms          # name shown in the Operation cell
      legacy: false               # true -> append " 🔒" to the name and use 🔒 marks
      pattern: "`http_call`"      # rendered verbatim into the Pattern cell
      component: sendSms.js       # filename in rtds/components, or null
      componentMark: "✅"          # ✅ | 🔒 | — | ⬜  (mark before the component link)
      runtimeCell: "JS twin `executeSendSms` (`SendSms_vocalls`)"  # verbatim Runtime cell
      seed: "✅"                   # ✅ | ⬜ | 🔒

Specs that are not catalog operations (the ``_*`` dispatcher/helper specs) carry
``catalog: null`` (or omit the block) and are listed in the fixed tail section.
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SPECS = REPO / "rtds" / "specs"
CATALOG = REPO / "rtds" / "docs" / "operations-catalog.md"

# Curated row order (matches the hand-authored catalog).
ROW_ORDER = [
    "sendSms", "sendEmail", "setVariables", "setAttributes",
    "guardRouting", "guardTui", "guard", "scheduler",
    "menu", "languageMenu", "playPrompt", "playAudio", "disconnect",
    "workgroupTransfer", "externalTransfer", "callback",
    "condition", "checkAttribute", "emergency", "flowJump",
    "manageCallCapacity", "updateSourceId", "ivrLogging", "callerDataEntry",
    "callbackAddRecord", "callbackInputPhoneNumber", "callbackMenuParticipate",
    "callbackTimeSlot",
]

# Map operation name -> spec filename (most are name.spec.md; scheduler is the
# exception, its spec is scheduler.spec.md but it renders as the checkSchedule row).
SPEC_FILE = {name: f"{name}.spec.md" for name in ROW_ORDER}

HEADER = """\
<!-- GENERATED by scripts/gen_catalog.py from rtds/specs/*.spec.md frontmatter — do not edit by hand. -->
# RTDS Operations Catalog

Inventory of every RTDS operation: its pattern, whether a Vocalls component and/or a runtime
twin exists, whether it has seed SQL, and links to the spec, component, and runtime handler.

Source of truth for status:
- **Component** — file present in [`rtds/components/`](../components/).
- **Runtime** — registration block in
  [`rtds_2_runtime.js`](../../projects/rtds-runtime/globalLibraries/active/rtds_2_runtime.js)
  (`registerRtdsOperation` = inline JS twin; `registerRtdsExit` = GUI-exit key; unregistered =
  not wired yet, `runStep` skips to `NextStep`).
- **Seed** — present in
  [`rtds/db_seed/seed_operations_vocalls_dictionary.sql`](../db_seed/seed_operations_vocalls_dictionary.sql).

Legend: ✅ present · ⬜ not yet · 🔒 legacy (superseded).

## Operations

| Operation | Pattern | Spec | Component | Runtime | Seed |
| --------- | ------- | ---- | --------- | ------- | ---- |
"""

TAIL = """\

## Canonical hand-built example (no operation spec)

| File | Purpose |
| ---- | ------- |
| [voicemaildetector.js](../components/voicemaildetector.js) | Reference hand-built mxGraph component cited throughout [component-mxgraph.md](../../conventions/component-mxgraph.md). Not a routing-table operation. |

## Runtime-internal / non-operation handlers

These specs describe the PureConnect dispatcher and helper sub-handlers, not RTDS operations —
the Vocalls runtime owns their behaviour natively (see
[runtime-architecture.md](runtime-architecture.md)). They have no component or registry entry.

- [_nalloRtds.spec.md](../specs/_nalloRtds.spec.md) — top-level dispatcher; replaced by the
  runtime's Script-node entry points.
- [_play.spec.md](../specs/_play.spec.md), [_promptLibraryGetDirList.spec.md](../specs/_promptLibraryGetDirList.spec.md),
  [events.spec.md](../specs/events.spec.md), [queueHandling.spec.md](../specs/queueHandling.spec.md).

> Keep this catalog in sync when you add/modify a component, wire a runtime handler, or add seed
> rows — see the "What to update when you change X" section in
> [CLAUDE.md](../../CLAUDE.md).
"""


def parse_frontmatter(path):
    """Minimal YAML-frontmatter reader. Returns dict or {} if none.

    Supports the small subset this project uses: top-level scalars and one
    nested ``catalog:`` mapping with scalar values. No external deps.
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end].strip("\n").splitlines()
    data = {}
    current = data
    for line in block:
        if not line.strip() or line.strip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        key, _, val = line.strip().partition(":")
        val = val.strip()
        if val == "" :
            data[key] = {}
            current = data[key]
        elif indent == 0:
            current = data
            data[key] = _scalar(val)
        else:
            current[key] = _scalar(val)
    return data


def _scalar(val):
    if val in ("null", "~", ""):
        return None
    if val in ("true", "True"):
        return True
    if val in ("false", "False"):
        return False
    if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
        return val[1:-1]
    return val


def render_row(cat):
    name = cat["operation"]
    name_cell = name + (" 🔒" if cat.get("legacy") else "")
    spec_link = f"[spec](../specs/{SPEC_FILE[name]})"
    comp = cat.get("component")
    mark = cat.get("componentMark", "⬜")
    if comp:
        comp_cell = f"{mark} [{comp}](../components/{comp})"
    else:
        comp_cell = mark
    return (
        f"| {name_cell} | {cat['pattern']} | {spec_link} | {comp_cell} | "
        f"{cat['runtimeCell']} | {cat['seed']} |"
    )


def render():
    # Build {operation: catalog-dict} from frontmatter.
    by_op = {}
    for spec in SPECS.glob("*.spec.md"):
        fm = parse_frontmatter(spec)
        cat = fm.get("catalog")
        if isinstance(cat, dict) and cat.get("operation"):
            by_op[cat["operation"]] = cat

    missing = [op for op in ROW_ORDER if op not in by_op]
    if missing:
        raise SystemExit(
            "gen_catalog: missing catalog frontmatter for: " + ", ".join(missing)
        )

    rows = [render_row(by_op[op]) for op in ROW_ORDER]
    body = HEADER + "\n".join(rows) + "\n" + TAIL

    # Match the catalog's committed newline style.
    raw = CATALOG.read_bytes() if CATALOG.exists() else b""
    nl = "\r\n" if b"\r\n" in raw else "\n"
    if nl == "\r\n":
        body = body.replace("\n", "\r\n")
    return body.encode("utf-8")


def main():
    want = render()
    have = CATALOG.read_bytes() if CATALOG.exists() else None
    if have == want:
        print("operations-catalog.md already in sync.")
        return
    CATALOG.write_bytes(want)
    print("operations-catalog.md regenerated from spec frontmatter.")


if __name__ == "__main__":
    main()
